name: Publish to npm

on:
  push:
    branches:
      - main  # Trigger on `main` or any branch of your choice

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Node.js version you are using
          registry-url: https://registry.npmjs.org  # Default npm registry URL

      # Cache node modules to speed up builds
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project (compile TypeScript to JavaScript)
      - name: Build project
        run: npm run build

      - name: Move dist/karya to root
        run: |
          mv dist/karya/* .
          rm -rf dist/karya

      # Configure Git user for versioning
      - name: Configure Git user for versioning
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Publish to npm
      - name: Publish package to npm
        run: |
          npm publish --access public  # Publish to npm registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
