name: Publish to GitHub Packages and npm

on:
  push:
    branches:
      - main   # Trigger on `main` or any branch of your choice

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Node.js version you are using
          registry-url: https://registry.npmjs.org  # Default registry for npm (used in second publish step)

      # Cache node modules to speed up builds
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

      # Configure Git user for versioning
      - name: Configure Git user for versioning
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Set npm registry for GitHub Packages
      - name: Set npm registry to GitHub Packages
        run: |
          npm config set registry https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      # Publish to GitHub Packages
      - name: Publish package to GitHub Packages
        run: |
          npm version patch # Increment the patch version
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub authentication token

      # Set npm registry back to npm (for publishing to npm registry)
      - name: Set npm registry to npm
        run: |
          npm config set registry https://registry.npmjs.org
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      # Publish to npm
      - name: Publish package to npm
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # npm authentication token

      # Optionally create a GitHub release
      - name: Create GitHub release
        id: create_release
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          gh release create $VERSION dist/* --title "Release $VERSION" --notes "Release version $VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
